2013/12/12 10:27:01 [error] [exception.CException] exception 'CException' with message 'The controller path "D:\xampp\htdocs\bwatch\work\protected\controllers\front" is not a valid directory.' in D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php:422
Stack trace:
#0 D:\xampp\htdocs\bwatch\yii\framework\base\CComponent.php(152): CWebApplication->setControllerPath('D:\xampp\htdocs...')
#1 D:\xampp\htdocs\bwatch\work\protected\components\WebApplicationEndBehavior.php(39): CComponent->__set('controllerPath', 'D:\xampp\htdocs...')
#2 D:\xampp\htdocs\bwatch\yii\framework\base\CComponent.php(561): WebApplicationEndBehavior->changeModulePaths(Object(CEvent))
#3 D:\xampp\htdocs\bwatch\work\protected\components\WebApplicationEndBehavior.php(32): CComponent->raiseEvent('onModuleCreate', Object(CEvent))
#4 D:\xampp\htdocs\bwatch\work\protected\components\WebApplicationEndBehavior.php(23): WebApplicationEndBehavior->onModuleCreate(Object(CEvent))
#5 [internal function]: WebApplicationEndBehavior->runEnd('front')
#6 D:\xampp\htdocs\bwatch\yii\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\bwatch\work\index.php(23): CComponent->__call('runEnd', Array)
#8 D:\xampp\htdocs\bwatch\work\index.php(23): CWebApplication->runEnd('front')
#9 {main}
REQUEST_URI=/bwatch/work/index.php
---
2013/12/12 11:34:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "index" was not found.' in D:\xampp\htdocs\bwatch\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 D:\xampp\htdocs\bwatch\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('index')
#1 D:\xampp\htdocs\bwatch\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 D:\xampp\htdocs\bwatch\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 D:\xampp\htdocs\bwatch\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 D:\xampp\htdocs\bwatch\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page/about')
#7 D:\xampp\htdocs\bwatch\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\xampp\htdocs\bwatch\work\protected\components\WebApplicationEndBehavior.php(25): CApplication->run()
#9 [internal function]: WebApplicationEndBehavior->runEnd('front')
#10 D:\xampp\htdocs\bwatch\yii\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#11 D:\xampp\htdocs\bwatch\work\index.php(23): CComponent->__call('runEnd', Array)
#12 D:\xampp\htdocs\bwatch\work\index.php(23): CWebApplication->runEnd('front')
#13 {main}
REQUEST_URI=/bwatch/work/index.php/site/page/about
---
2013/12/13 11:04:17 [error] [exception.CException] exception 'CException' with message 'Alias "path.alias.to.booster.components.Bootstrap" is invalid. Make sure it points to an existing directory or file.' in D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php:347
Stack trace:
#0 D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php(196): YiiBase::import('path.alias.to.b...', true)
#1 D:\xampp\htdocs\bwatch\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 D:\xampp\htdocs\bwatch\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 D:\xampp\htdocs\bwatch\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php(125): CApplication->__construct('D:\xampp\htdocs...')
#5 D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'D:\xampp\htdocs...')
#6 D:\xampp\htdocs\bwatch\work\index.php(23): YiiBase::createWebApplication('D:\xampp\htdocs...')
#7 {main}
REQUEST_URI=/bwatch/work/index.php/site/login
HTTP_REFERER=http://localhost/bwatch/work/index.php/site/page?view=about
---
2013/12/13 11:08:51 [error] [exception.CException] exception 'CException' with message 'Alias "gii.GiiModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php:322
Stack trace:
#0 D:\xampp\htdocs\bwatch\yii\framework\YiiBase.php(196): YiiBase::import('gii.GiiModule', true)
#1 D:\xampp\htdocs\bwatch\yii\framework\base\CModule.php(282): YiiBase::createComponent('gii.GiiModule', 'gii', NULL, Array)
#2 D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php(337): CModule->getModule('gii')
#3 D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php(276): CWebApplication->createController('gii/default/ind...')
#4 D:\xampp\htdocs\bwatch\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/default/ind...')
#5 D:\xampp\htdocs\bwatch\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\xampp\htdocs\bwatch\work\protected\components\WebApplicationEndBehavior.php(25): CApplication->run()
#7 [internal function]: WebApplicationEndBehavior->runEnd('front')
#8 D:\xampp\htdocs\bwatch\yii\framework\base\CComponent.php(261): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\bwatch\work\index.php(23): CComponent->__call('runEnd', Array)
#10 D:\xampp\htdocs\bwatch\work\index.php(23): CWebApplication->runEnd('front')
#11 {main}
REQUEST_URI=/bwatch/work/index.php/gii/default/index
---
